-- The one live sync a feature has, beside the append-only audit V9 keeps.
--
-- A sync that hits a conflict leaves three things behind: a React `useState`
-- that dies on the next navigation, a `feature_syncs` row whose JSON was read
-- for exactly one field, and a real worktree on disk with `MERGE_HEAD` set
-- that nothing in the UI names. Only the third survives a reload, and the only
-- thing that ever cleaned it up was the next sync force-removing it. V9 cannot
-- hold this: an append-only log can shadow an entry but never retract one, so
-- "is this feature mid-sync" would be a whole-log scan and a fold, and
-- "abort it" would have no row to close. V9 stays exactly as it is.
--
-- `feature_id` is the primary key rather than a surrogate id because "at most
-- one sync in flight per feature" is the invariant, and a key enforces what a
-- comment could only ask for. History is not lost — every outcome still
-- appends its `feature_syncs` row.
--
-- The FK is real here, unlike V40's deliberate refusal: a workflow id is
-- re-generated by the remote runner, but a feature id is client-chosen and
-- carried verbatim through the `RunSpec`. A deleted feature's sync is not a
-- sync, so it cascades.
--
-- **The row is a claim; the working tree is the authority.** Every read
-- reconciles the stored status against what is actually on disk
-- (`domain::sync_session::reconcile`), because a process that dies mid-merge
-- writes no closing row and a user who resolves the tree by hand tells this
-- table nothing.
CREATE TABLE IF NOT EXISTS sync_sessions (
    feature_id            TEXT PRIMARY KEY,
    -- Which filesystem `repo_dir` and `worktree_path` are on. `LOCAL_MACHINE`
    -- for the desktop host, which by policy has no `machines` row (V38), so
    -- this carries no foreign key — the same reasoning as
    -- `worktree_cleanup_queue.machine_id` (V39).
    machine_id            TEXT NOT NULL,
    -- The clone the worktree was cut from. Stored rather than re-derived
    -- because tearing the session down needs it (`git -C <repo> worktree
    -- remove`) and re-resolving it means the project row, the repository row
    -- and, on a remote, a `resolve_home` round trip — none of which a teardown
    -- should be able to fail on.
    repo_dir              TEXT NOT NULL,
    feature_branch        TEXT NOT NULL,
    base_branch           TEXT NOT NULL,
    -- syncing | up_to_date | merged | blocked | conflicted | resolving |
    -- resolved | resolution_failed | aborted
    status                TEXT NOT NULL,
    -- The throwaway worktree the merge runs in. NULL until one is provisioned,
    -- and equal to `repo_dir` when the feature branch was already checked out
    -- in the clone — `provision_sync_worktree` returns the clone itself in
    -- that case, so "worktree_path is set" is not "a throwaway tree exists"
    -- and every teardown goes through `discard_sync_worktree`, whose guard is
    -- what stops a recursive delete of the user's checkout.
    worktree_path         TEXT,
    -- The feature branch's tip *before* the merge. Persisted at sync time
    -- because it is the only base a review diff can use: `merge_commit^..
    -- merge_commit` reads correctly and goes silently wrong the moment a
    -- resolver adds a follow-up commit, and by then the pre-merge tip is
    -- unreachable from anything the row still holds.
    head_before           TEXT,
    merge_commit_sha      TEXT,
    -- JSON array of `ConflictFile` (domain/models/merge.rs). NULL and `[]`
    -- differ: NULL is "never measured", `[]` is "git answered nothing", which
    -- is what a porcelain read returns on any transport error.
    conflict_files        TEXT,
    -- Verbatim stderr from the failing git invocation, rendered rather than
    -- summarised: why a sync is blocked is often not a conflict at all, and
    -- only git knows how to say it.
    raw_error             TEXT,
    -- Resolution attempts against this session. Any cap is applied by the
    -- reader, never by a WHERE clause, so "capped" and "still retried" cannot
    -- disagree (`worktree_cleanup_queue`'s rule).
    attempts              INTEGER NOT NULL DEFAULT 0,
    created_at            INTEGER NOT NULL,
    updated_at            INTEGER NOT NULL,
    FOREIGN KEY(feature_id) REFERENCES features(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sync_sessions_status
    ON sync_sessions(status, updated_at DESC);
